AWSTemplateFormatVersion: 2010-09-09

Description: Este template es para crear una EC2 y asociarla a una red existente

#Metadata:

Parameters:
  Ec2Type:
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3a.xlarge
    Default: t2.medium
    Description: Tipo de EC2
    ConstraintDescription: Debe ser un tipo de ec2 valido
    Type: String

  KeyName:
    Description: Llave para usar en la EC2
    ConstraintDescription: Debe ser un nombre que no exista en sus llaves
    Type: String

  TypeVolumen1:
    Default: gp3
    Description: Ingrese el tipo de EBS
    AllowedValues:
      - gp2
      - gp3
      - io1
      - io2
    Type: String

  SizeVolumen1:
    Default: 20
    Description: Por favor ingrese el tamaño del volumen EBS
    Type: String

  TypeVolumen2:
    Default: gp3
    Description: Ingrese el tipo de EBS
    AllowedValues:
      - gp2
      - gp3
      - io1
      - io2
    Type: String

  SizeVolumen2:
    Default: 20
    Description: Por favor ingrese el tamaño del volumen EBS
    Type: String


Resources:

  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref KeyName

  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e83be366243f524a
      InstanceType: !Ref Ec2Type
      KeyName: !Ref NewKeyPair
      SecurityGroupIds:
           - sg-0715a6f853ecc9937
      SubnetId: subnet-0dfaceb17872070d6
      BlockDeviceMappings:
      - DeviceName: /dev/sdm
        Ebs:
          VolumeType: !Ref TypeVolumen1
          DeleteOnTermination: true
          VolumeSize: !Ref SizeVolumen1
      - DeviceName: /dev/sdp
        Ebs:
          VolumeType: !Ref TypeVolumen2
          DeleteOnTermination: true
          VolumeSize: !Ref SizeVolumen2
      Tags:
        - Key: Name
          Value: EC2 PRUEBA

Outputs:
  EC2: 
    Description: EC2 ID
    Export:
      Name: !Sub ${AWS::StackName}-EC2
    Value: !Ref EC2